name: 'Setup  Node + Install Dependencies'
description: 'Setup  Node + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install Dependences
      run: npm install
      shell: bash
